# Generated by Django 4.0.2 on 2022-07-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.category'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
