# Generated by Django 4.0.2 on 2022-07-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_alter_orders_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='isGlutenFree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='isVegeterian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
