# Generated by Django 4.0.6 on 2022-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_dish_isglutenfree_dish_isvegeterian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='foodapp.dish'),
        ),
    ]
